version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: vanguard
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vanguard
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4g
          cpus: "10.0"
        reservations:
          memory: 4g
          cpus: "10.0"
      restart_policy:
        condition: on-failure

volumes:
  mysql_data: